[libraries]
jetbrains-annotations = 'org.jetbrains:annotations:26.0.2-1'

yunan9-commons = 'io.github.yunan9:commons:0.1.3-SNAPSHOT'
yunan9-pointers = 'io.github.yunan9:pointers:1.0.1'

[bundles]
yunan9-series = ['yunan9-commons', 'yunan9-pointers']